//DEFINIR ACTIONS
export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
export const GET_TYPES = "GET_TYPES";
export const FILTER_POKEMONS_BY_TYPE = "FILTER_POKEMONS_BY_TYPE";
export const FILTER_POKEMONS_BY_ORIGIN = "FILTER_POKEMONS_BY_ORIGIN";
export const SORT_POKEMONS = "SORT_POKEMONS";
export const SORT_POKEMONS_BY_ATTACK = "SORT_POKEMONS_BY_ATTACK";
export const CLEAR_POKEMON_BY_NAME = "CLEAR_POKEMON_BY_NAME";
