//DEFINIR ACTIONS
export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
export const FILTER_POKEMONS_BY_TYPE = "FILTER_POKEMONS_BY_TYPE";
export const FILTER_POKEMONS_BY_STORAGE = "FILTER_POKEMONS_BY_STORAGE";
export const SORT_POKEMONS = "SORT_POKEMONS";
