
//DEFINIR ACTIONS
export const  GET_POKEMONS = "GET_POKEMONS";
export const  GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const  GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
export const GET_ALL_TYPES = "GET_ALL_TYPES"; 
export const FILTER_POKEMONS = "FILTER_POKEMONS"; 
export const SORT_POKEMONS = "SORT_POKEMONS"; 
export const GET_DETAILS = "GET_DETAILS";
